import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}>

          {/* app UI layer */}
          <div className="relative z-10 flex h-screen overflow-hidden">
            <Sidebar />

            <div className="flex-1 min-h-0 overflow-y-auto">
              <div className="mx-auto w-full max-w-6xl p-8">
                {children}
              </div>
            </div>
          </div>
        </body> 
    </html>
  );
}
