-- =============================================================================
-- AI ASSISTANT TABLES
-- Database schema for the Jarvis AI assistant feature.
--
-- Tables:
-- 1. ai_conversations - Groups related chat messages
-- 2. ai_messages - Individual chat messages with metadata
-- 3. user_ai_preferences - User settings for AI behavior
-- 4. ai_insights - Proactive insights generated by AI
--
-- LEARNING: Database Design for AI Features
-- ------------------------------------------
-- AI features need to store:
-- - Conversation history (for context in future chats)
-- - User preferences (to personalize responses)
-- - Generated insights (for proactive notifications)
--
-- Key considerations:
-- - RLS (Row Level Security) ensures users only see their own data
-- - JSONB for flexible metadata storage
-- - Timestamps for chronological ordering
-- - Foreign keys for referential integrity
-- =============================================================================

-- -----------------------------------------------------------------------------
-- AI CONVERSATIONS TABLE
-- Groups related messages into conversations.
-- Each conversation has a title (auto-generated or user-set) and timestamps.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT, -- Optional title, can be auto-generated from first message
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fetching user's conversations
CREATE INDEX IF NOT EXISTS idx_ai_conversations_user_id ON ai_conversations(user_id);

-- Index for ordering by recency
CREATE INDEX IF NOT EXISTS idx_ai_conversations_created_at ON ai_conversations(created_at DESC);

-- RLS: Users can only access their own conversations
ALTER TABLE ai_conversations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own conversations"
  ON ai_conversations FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own conversations"
  ON ai_conversations FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own conversations"
  ON ai_conversations FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own conversations"
  ON ai_conversations FOR DELETE
  USING (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- AI MESSAGES TABLE
-- Individual messages within a conversation.
-- Stores role (user/assistant), content, and metadata (tokens, actions, etc.)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID REFERENCES ai_conversations(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fetching messages in a conversation
CREATE INDEX IF NOT EXISTS idx_ai_messages_conversation_id ON ai_messages(conversation_id);

-- Index for ordering messages chronologically
CREATE INDEX IF NOT EXISTS idx_ai_messages_created_at ON ai_messages(created_at);

-- RLS: Users can only access their own messages
ALTER TABLE ai_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own messages"
  ON ai_messages FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own messages"
  ON ai_messages FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Messages are generally immutable, but allow deletion
CREATE POLICY "Users can delete own messages"
  ON ai_messages FOR DELETE
  USING (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- USER AI PREFERENCES TABLE
-- Stores user settings for AI behavior.
-- Includes communication style, proactive notifications, etc.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_ai_preferences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  proactive_enabled BOOLEAN DEFAULT true,
  communication_style TEXT DEFAULT 'friendly' CHECK (communication_style IN ('friendly', 'professional', 'minimal')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: Users can only access their own preferences
ALTER TABLE user_ai_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own preferences"
  ON user_ai_preferences FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own preferences"
  ON user_ai_preferences FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own preferences"
  ON user_ai_preferences FOR UPDATE
  USING (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- AI INSIGHTS TABLE
-- Stores proactive insights generated by the AI.
-- These are shown to users as notifications/suggestions.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  insight_type TEXT NOT NULL CHECK (insight_type IN (
    'optimal_focus_time',
    'workload_warning',
    'streak_risk',
    'break_reminder',
    'progress_celebration',
    'habit_reminder',
    'task_suggestion',
    'planning_reminder'
  )),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high')),
  action_type TEXT, -- Optional: type of action to execute
  action_payload JSONB, -- Optional: payload for the action
  shown_at TIMESTAMPTZ, -- When the insight was shown to user
  dismissed_at TIMESTAMPTZ, -- When user dismissed the insight
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fetching user's pending insights
CREATE INDEX IF NOT EXISTS idx_ai_insights_user_pending
  ON ai_insights(user_id, created_at DESC)
  WHERE shown_at IS NULL OR dismissed_at IS NULL;

-- Index for cleaning up old insights
CREATE INDEX IF NOT EXISTS idx_ai_insights_created_at ON ai_insights(created_at);

-- RLS: Users can only access their own insights
ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own insights"
  ON ai_insights FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own insights"
  ON ai_insights FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own insights"
  ON ai_insights FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own insights"
  ON ai_insights FOR DELETE
  USING (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- TRIGGER: Update updated_at timestamp
-- Automatically updates the updated_at field when a row is modified.
-- -----------------------------------------------------------------------------

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to tables with updated_at
DROP TRIGGER IF EXISTS update_ai_conversations_updated_at ON ai_conversations;
CREATE TRIGGER update_ai_conversations_updated_at
  BEFORE UPDATE ON ai_conversations
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_user_ai_preferences_updated_at ON user_ai_preferences;
CREATE TRIGGER update_user_ai_preferences_updated_at
  BEFORE UPDATE ON user_ai_preferences
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------------------------------
-- COMMENTS
-- Document the tables for future reference.
-- -----------------------------------------------------------------------------
COMMENT ON TABLE ai_conversations IS 'Groups of related AI chat messages';
COMMENT ON TABLE ai_messages IS 'Individual chat messages with the AI assistant';
COMMENT ON TABLE user_ai_preferences IS 'User settings for AI assistant behavior';
COMMENT ON TABLE ai_insights IS 'Proactive insights and suggestions generated by AI';

COMMENT ON COLUMN ai_messages.metadata IS 'JSON containing: promptTokens, completionTokens, actions, processingTimeMs, model';
COMMENT ON COLUMN ai_insights.action_type IS 'Type of action to execute: CREATE_TASK, START_FOCUS, NAVIGATE, etc.';
COMMENT ON COLUMN ai_insights.action_payload IS 'JSON payload for the action, e.g., {"title": "Task name", "priority": "high"}';
